#ifndef HEADING_TUNING_H
#define HEADING_TUNING_H
/* Controller units: radians, radians/second, seconds. Preserve validated gains. */
#define HEADING_RAD_PER_DEG 0.017453292519943295f
#define HEADING_MOVING_TOLERANCE_DEG 0.2f
#define HEADING_STATIC_TOLERANCE_DEG 0.1f
#define HEADING_TRAVEL_KP_SCALE 1.5f
#define HEADING_START_TURN_KP 8.0f
#define HEADING_TRAVEL_DAMPING_SCALE (7.0f / 3.0f)
#define HEADING_FINE_KP 2.0f
#define HEADING_FINE_DAMPING 0.08f
#define HEADING_FINE_LIMIT (2.0f * HEADING_RAD_PER_DEG)
#define HEADING_FINE_RANGE (3.0f * HEADING_RAD_PER_DEG)
#define HEADING_HOLD_LIMIT (1.0f * HEADING_RAD_PER_DEG)
#define HEADING_FINE_SLEW (5.0f * HEADING_RAD_PER_DEG)
#define HEADING_HOLD_ENTRY (0.5f * HEADING_RAD_PER_DEG)
#define HEADING_SETTLE_RATE (2.0f * HEADING_RAD_PER_DEG)
#define HEADING_SETTLE_CYCLES 10U
#define HEADING_HOLD_STOP_RATE (0.5f * HEADING_RAD_PER_DEG)
#endif
